
spring.application.name=beautysalonRESTAPI


server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=beautysalon;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=11112222
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
